# Generated by Django 3.0.5 on 2020-04-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20200421_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='videopost',
            name='title',
            field=models.CharField(default='Title', max_length=100),
            preserve_default=False,
        ),
    ]
