# Generated by Django 3.0.5 on 2020-04-21 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0005_auto_20200421_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentpost',
            name='time',
            field=models.CharField(max_length=10),
        ),
    ]
