# Generated by Django 3.0.5 on 2020-04-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_userhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='owner',
            field=models.IntegerField(),
        ),
    ]
